import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Header from "../components/Header/Header";
import Layout from "../components/Layout/Layout";
import TaskList, { TaskProps } from "../components/TaskList/TaskList";

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Sintaxis Todo App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Header />
        <TaskList />
      </Layout>
    </div>
  );
};

export default Home;
